name: emarkproject
version: master
summary: decentralized peer-to-peer platform
description: |
  The eMark Project is a decentralized peer-to-peer platform, created under an
  open source license, featuring a built-in cryptocurrency, end-to-end
  encrypted messaging and decentralized marketplace. The decentralized network
  aims to provide anonymity and privacy for everyone through a simple
  user-friendly interface by taking care of all the advanced cryptography in
  the background.
grade: devel
confinement: strict

apps:
  emarkproject:
    command: desktop-launch $SNAP/usr/bin/eMark
    plugs: [network, network-bind, unity7]

parts:
  emarkproject:
    source: .
    plugin: qmake
    qt-version: qt4
    build-packages:
      - build-essential
      - g++
      - libboost-all-dev
      - libboost-dev
      - libboost-filesystem-dev
      - libboost-program-options-dev
      - libboost-system-dev
      - libboost-thread-dev
      - libdb++-dev
      - libminiupnpc-dev
      - libprotobuf-dev
      - libqrencode-dev
      - libssl-dev
      - qt4-dev-tools
      - qt4-default
      - qt4-qmake
      - qtbase5-dev-tools
      - qttools5-dev-tools
    after: [desktop-qt4]
